"""Add dashboard fields to Booking model

Revision ID: 7ca767877304
Revises: 
Create Date: 2025-05-19 13:31:26.230000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca767877304'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('distribution_channel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lead_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('special_requests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_repeated_guest', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('is_repeated_guest')
        batch_op.drop_column('special_requests')
        batch_op.drop_column('lead_time')
        batch_op.drop_column('distribution_channel')
        batch_op.drop_column('guest_country')

    # ### end Alembic commands ###
